// Auto-generated by OpenLane
module Systolic4x4_serial_io(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input start,
  input A_in_serial_data,
  input A_in_serial_clk,
  input A_in_frame_sync,
  input B_in_serial_data,
  input B_in_serial_clk,
  input B_in_frame_sync,
  output C_out_serial_data,
  output C_out_serial_clk,
  output C_out_frame_sync,
  output done
);
endmodule
